### ISSUE TITLE
Ne mešajta tab-ov in presledkov.

### ISSUE THREAD

**Issue by andrejbauer** [janzmazek/Cram#7]
Ko poženem vajjin program dobim:

```
$ python3 cram.py 
  File "cram.py", line 29
    for i in range(VELIKOST_PLOSCE):
                                   ^
TabError: inconsistent use of tabs and spaces in indentation
```

To se zgodi, ker uporabljate tabulatorje. Prosim da ima koda samo presledke. Nastavita si urejevalnik, da ne bo uporabjal tabov. Preberita si http://stackoverflow.com/questions/120926/why-does-python-pep-8-strongly-recommend-spaces-over-tabs-for-indentation

**Comment by rokgersak** [comment]
Od sedaj samo presledki. https://github.com/janzmazek/Cram/commit/34a23c834b2d7ff6780e408118958972a735e9f0
